### PR TITLE
TemperatureSlider Widget

### PR DESCRIPTION
**Pull request by henryrossiter**
- Add TemperatureSlider widget
    - Uses ```inputType: 'TemperatureSlider '```
- Lint Slider widget

### CODE REVIEW

**Comment by henryrossiter** [comment]
> should it be a custom slider component, instead of just a temperature one? I see other applications, for sure. What's your thought on that?

I created a [ContinuousSlider ](https://github.com/ChildMindInstitute/mindlogger-app/pull/996) widget for MindLogger parent repository yesterday as well. For that component, I simply modified the existing Slider widget with a smaller ```step```.

Ideally, the Slider and ContinuousSlider would both allow configurable units, step, and labels. However, I haven't yet figured out the best way to do this within the MindLogger JSONLD schema. Units are pretty important for our case but I did not want to hardcode any units into the ContinuousSlider widget, so I created this specific widget that is specifically designed for our case.

> maybe step size could be parametrized too, if 0). Or be based on the width of the component, instead of 200 steps between min and max

Yeah, this is a good idea. I think it should be parameterized (with a default value ofc). However, I think we can leave this for another pull request because it may take some effort to do it correctly and is not super important for our case.

> do you think it would be good to have a "number format" component prop?

Good catch, the long floats are pretty ugly. I'm not sure it needs to be a prop- I'll add a component function to round the value based on the step size.

> should the conditional currentVal >= minimumValue on the SliderComponent value also consider the max value?

Yeah, it's probably smart to check for this bad input. I'll add this.

**Comment by henryrossiter** [comment]
> I do not see the point of the itemList in this component, since we have the min and max values. are they just to provide an icon and (re)compute the min and max?

```itemList``` also provides the labels. It is not always the case that the labels are numeric.

**Comment by henryrossiter** [comment]
@anibalsolon 

Thoughts on this bit of rounding logic? Rounds value based on the step size.
```
const numDigits = Math.ceil(
  Math.abs(
    Math.log10(stepSize),
  ),
);
return currentValue.toFixed(numDigits);
```

**Comment by anibalsolon** [comment]
The logic looks great! I am fine with this instead of a function/format, clever one :)

Ok, I understand about the `itemList`. Is that the same case, for a continuous slider?

Got it, about the components rationale. Not for this PR, more as a curiosity, but how editable is the ML schemas? I guess schema.org provides the entities for these properties for the slider.

**Comment by henryrossiter** [comment]
> Ok, I understand about the `itemList`. Is that the same case, for a continuous slider?

Yeah, it should be possible for the itemList labes to be qualitative values instead of numeric. I haven't tested this type of schema with a continuous slider yet, but I don't see any reason it wouldn't work.
 
> Not for this PR, more as a curiosity, but how editable is the ML schemas? I guess schema.org provides the entities for these properties for the slider.

I believe we would just need to find or mint iri's for the variables we want to parameterize. I'm not sure how difficult it would be, it may require some research.

**Pull request merged**
